projects/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'projects'

urlpatterns = [

	path('', views.index, name='index'),
	path('<int:videos_id>/', views.detail, name='detail'),
	path('maintenance/', views.maintenance, name='maintenance'),

]

yamete/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('', include('projects.urls', namespace='projects')),
	path('static/images/', include('projects.urls', namespace='images')),
    path('admin/', admin.site.urls),
]

projects/models.py
from django.db import models


class Episodes(models.Model):
	number = models.CharField(max_length=100)
	ep_link = models.URLField()

	def __str__(self):
		return self.number

#class Summary(models.Model):
#	title = models.CharField(null=True, blank=True, max_length=100)
#	genre = models.TextField(null=True, blank=True)
#	author = models.TextField(null=True, blank=True)
#	release = models.TextField(null=True, blank=True)

#	def __str__(self):
#		return self.title

class Videos(models.Model):
	photo = models.ImageField(upload_to='images', default='#')
	title = models.CharField(null=True, blank=True, max_length=100)
	description = models.TextField(null=True, blank=True)
	season = models.DecimalField(max_digits=10, decimal_places=0, null=True, blank=True)
	eps_link = models.ManyToManyField(Episodes)
	genre = models.TextField(null=True, blank=True)
	author = models.TextField(null=True, blank=True)
	release = models.TextField(null=True, blank=True)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.title

	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
	videos = models.ForeignKey(Videos, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text

projects/views.py
from django.shortcuts import get_object_or_404, render, redirect
from .models import Videos, Episodes, Choice

def index(request):
	#latest_videos_list = Videos.objects.order_by('-pub_date')[:5]
	videos_list = Videos.objects.all()
	#videos = Videos.objects.all()
	context = {'videos_list': videos_list}
	#context = {'videos': videos}
	return render(request, 'proj/index.html', context)

def detail(request, videos_id):
	videos = get_object_or_404(Videos, pk=videos_id)
	episodes = Episodes.objects.all()
	return render(request, 'proj/detail.html', {'videos': videos, 'episodes':episodes})

def maintenance(request):
	return render(request, 'proj/maintenance.html')

projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  

</head>
<style>
#copyright {
    position: fixed;
    bottom: 0;
    left: 21%;
    font-weight: bolder;
    font-size: 10px;
    transition: 700ms;
}

#webbody {

    position: absolute;
    padding: 5px;
    top: 8%;
    left: 2%;
    color: white;
    background-color: transparent;
    border-style: groove;
    width: 375px;
    height: 1300px;
    overflow: scroll;

}

#container {
    
    width: 362px;
    height: 200px;
    left: 0%;
    border-style: solid;
    overflow: hidden;
    
}
</style>
<body style="font-family:sans-serif;
    background:rgb(27,27,28);
    color:white;height:1400px">
    
    <nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
        <button type="button"class="navbar-toggle"data-toggle="collapse"
        data-target="#example-navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
    </button>
      <a class="navbar-brand" style="border-width:1px;border-color:#ffffff;color:white;" href="#">Yamete-Kun</a>
    </div>
    <div class="collapse navbar-collapse" id="example-navbar-collapse">
      
      <ul class="nav navbar-nav navbar-right">
           <ul class="nav navbar-nav"style="padding-left:10px;">
        <li class="active"><a href="#">HOME</a></li>
        <li class="#"><a href="#">Read Comics</a></li>
        <li class="#"><a href="#">Browse</a></li>
        <li class="#"><a href="#">ABOUT</a></li>

        <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Join<span class="caret"></span></a>
          <ul class="dropdown-menu" style="padding-left:5px;">
            <li><a href="#">SignIn</a></li>
            <li><a href="#">SignUp</a></li>
            <li><a href="#">Premium</a></li>

          </ul>
        </li>

      </ul>  
      </ul>
    </div>
  </div>
</nav>
     
<div class="container">
 
  
</div>

<footer>
<div id="copyright">
                <p>COPYRIGHT &copy <script>document.write(new Date().getFullYear())</script> ALL RIGHTS ® RESERVED.</p>
            </div>
</footer>
</body>
</html>

projects/templates/comblog.html
{% load  static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Add a gray background color with some padding */
body {
  font-family: Arial;
  padding: 20px;
  background: #f1f1f1;
}

/* Header/Blog Title */
.header {
  padding: 30px;
  font-size: 40px;
  text-align: center;
  background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
  float: left;
  width: 75%;
}

/* Right column */
.rightcolumn {
  float: left;
  width: 25%;
  padding-left: 20px;
}

/* Fake image */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Add a card effect for articles */
.card {
   background-color: white;
   padding: 20px;
   margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Footer */
.footer {
  padding: 20px;
  text-align: center;
  background: #ddd;
  margin-top: 20px;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
  .leftcolumn, .rightcolumn {   
    width: 100%;
    padding: 0;
  }
}
</style>
</head>
<body>

<div class="header">
  <h2>Blog Name</h2>
</div>

<div class="row">
  <div class="leftcolumn">
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Dec 7, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
    <div class="card">
      <h2>TITLE HEADING</h2>
      <h5>Title description, Sep 2, 2017</h5>
      <div class="fakeimg" style="height:200px;">Image</div>
      <p>Some text..</p>
      <p>Sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco.</p>
    </div>
  </div>
  <div class="rightcolumn">
    <div class="card">
      <h2>About Me</h2>
      <div class="fakeimg" style="height:100px;">Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    </div>
    <div class="card">
      <h3>Popular Post</h3>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Some text..</p>
    </div>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

projects/templates/halfblog.html
{% load  static %}
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
* {
  box-sizing: border-box;
}

/* Add a gray background color with some padding */
body {
  font-family: Arial;
  padding: 20px;
  background: #f1f1f1;
}

/* Header/Blog Title */
.header {
  padding: 30px;
  font-size: 40px;
  text-align: center;
  background: white;
}

/* Create two unequal columns that floats next to each other */
/* Left column */
.leftcolumn {   
  float: left;
  width: 75%;
}

/* Right column */
.rightcolumn {
  float: left;
  width: 25%;
  padding-left: 20px;
}

/* Fake image */
.fakeimg {
  background-color: #aaa;
  width: 100%;
  padding: 20px;
}

/* Add a card effect for articles */
.card {
   background-color: white;
   padding: 20px;
   margin-top: 20px;
}

/* Clear floats after the columns */
.row:after {
  content: "";
  display: table;
  clear: both;
}

/* Footer */
.footer {
  padding: 20px;
  text-align: center;
  background: #ddd;
  margin-top: 20px;
}

/* Responsive layout - when the screen is less than 800px wide, make the two columns stack on top of each other instead of next to each other */
@media screen and (max-width: 800px) {
  .leftcolumn, .rightcolumn {   
    width: 100%;
    padding: 0;
  }
}
</style>
</head>
<body>

<div class="header">
  <h2>Blog Name</h2>
</div>

  <div class="rightcolumn">
    <div class="card">
      <h2>About Me</h2>
      <div class="fakeimg" style="height:100px;">Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    </div>
    <div class="card">
      <h3>Popular Post</h3>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Some text..</p>
    </div>
  </div>
</div>

<div class="footer">
  <h2>Footer</h2>
</div>

</body>
</html>

projects/templates/proj/detail.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<title></title>
	<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<title>BCC|YAMETE</title>
</head>

<body style="background-color:#000000;color:#ffffff;font-family:'Source Code Pro', monospace;">

<a href="#" style="text-decoration:none;color:#ffffff;"><h3 style="padding:2px;">Yamete <span style="color:#000000;width:20px;height:20px;background-color:#FF9600;">Projects</span></h3></a>
<a href="/maintenance" style="text-decoration:none;"><h6 style="float:right;padding:5px;background-color:#FF9600;color:#000000;">Subscribe Premium</h6></a>
<hr style="color:#ffffff;">
<div class="container" style="width:320px;height:500px;padding:2px;text-align:center;overflow:auto;">
				<div class='card' style='width:310px;height:450px;background-color:transparent;padding:5px;'><a href="/static{{videos.photo.url}}"><img src="/static{{videos.photo.url}}" style="width:180px;height:130px;">
				</a><p class="title" style="color:#FF9600;">{{videos.title}}</p>
					<hr>
					<div class="summary" style="width:300px;padding:2px;">
					<p style="color:#000000;background-color:#FF9600;">Summary</p>
					{% if videos.genre %}
						<p>Genre(s) - {{videos.genre}}</p>
						<p>Author(s) - {{videos.author}}</p>
						<p>Release - {{videos.release}}</p>
						<a id="see_more"><p style="color:#000000;background-color:#33FF00;">See More <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M8 4a.5.5 0 0 1 .5.5v5.793l2.146-2.147a.5.5 0 0 1 .708.708l-3 3a.5.5 0 0 1-.708 0l-3-3a.5.5 0 1 1 .708-.708L7.5 10.293V4.5A.5.5 0 0 1 8 4z"/>
</svg></p></a>
					<div class="description" id="desc" style="width:300px;padding:2px;">{{videos.description}}
						</div>
					{% else %}
						<p>Summary Not Available!</p>
						{% endif %}
					</div>
					<p style="color:#000000;background-color:#FF9600;">Episodes</p>
					{% if videos %}
					{% for eps in videos.eps_link.filter %}
						<a href="{{eps.ep_link}}"><p class="btn btn-warning">{{eps.number}}</p></a>
					{% endfor %}
					{% else %}
					<p>No Episodes Available!</p>
					{% endif %}
					<br>
				</div>
			</div>
		<hr style="color:#ffffff">
<script>
	$(document).ready(function(){
		$("h6").mouseover(function(){
			$("h6").css("background-color", "#68FF00");
		});
		$("h6").mouseout(function(){
			$("h6").css("background-color", "#FF9600");
		});
		$("h3").mouseover(function(){
			$("h3").css("color", "#68FF00");
		});
		$("h3").mouseout(function(){
			$("h3").css("color", "#ffffff");
		});
		$("span").mouseover(function(){
			$("span").css("background-color", "#68FF00");
		});
		$("span").mouseout(function(){
			$("span").css("background-color", "#FF9600");
		});
		$("#desc").hide();
		$("#see_more").click(function(){
    		$("#desc").toggle();
  		});
   
	});

</script>
</body>

</html>

projects/templates/proj/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>BCC|Yamete</title>
</head>
<body style="background-color:#000000;color:#ffffff;font-family:'Source Code Pro', monospace;">
		<a href="#" style="text-decoration:none;color:#ffffff;"><h3 style="padding:2px;">Yamete <span style="color:#000000;width:20px;height:20px;background-color:#FF9600;">Projects</span></h3></a>
	<a href="maintenance/" style="text-decoration:none;"><h6 style="float:right;padding:5px;background-color:#FF9600;color:#000000;">Subscribe Premium</h6></a>
	<hr style="color:#ffffff">
{% if videos_list %}
{% for videos in videos_list %}
<div class="container" style="width:320px;height:220px;padding:2px;text-align:center;">
				<div class='card' style='border-style:groove;border-color:#ffffff;width:320px;height:210px;background-color:transparent;padding:2px;'><a href="/static{{videos.photo.url}}"><img src="/static{{videos.photo.url}}" style="width:180px;height:130px;"></a><p>{{videos.title}}</p>
					{% if videos.season %}
					<a href="{% url 'projects:detail' videos.id %}">
				<button type="button" class="btn btn-warning" style="padding:2px;">Season-{{videos.season}}</button>
			</a>
			{% else %}
			<a href="{% url 'projects:detail' videos.id %}">
				<button type="button" class="btn btn-warning" style="padding:2px;">WATCH</button>
			</a>
			{% endif %}
		</div>
			</div>

{% endfor %}

		<hr style="color:#ffffff">

{% else %}
<p>No videos are available.</p>
{% endif %}

<script>
	$(document).ready(function(){
		$("h6").mouseover(function(){
			$("h6").css("background-color", "#68FF00");
		});
		$("h6").mouseout(function(){
			$("h6").css("background-color", "#FF9600");
		});
		$("h3").mouseover(function(){
			$("h3").css("color", "#68FF00");
		});
		$("h3").mouseout(function(){
			$("h3").css("color", "#ffffff");
		});
		$("span").mouseover(function(){
			$("span").css("background-color", "#68FF00");
		});
		$("span").mouseout(function(){
			$("span").css("background-color", "#FF9600");
		});
	});

</script>
</body>
</html>

projects/templates/proj/maintenance.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<title></title>
	<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
<title>BCC|YAMETE</title>
</head>
<body>
	<body style="background-color:#000000;color:#ffffff;">
		<h1>UnderConstruction</h1>
	</body>
</body>
</html>